creating Room endpoint
Stanislav-Stoychev01/Desk-Reserve pull request #5
Opened 2023-10-30 13:45 UTC by desiggancheva

2023-10-30 13:50 UTC, MartinPetrakiev commented on DeskReserve/Controllers/RoomsController.cs
Although the logic in each endpoint of the controller is not complex, try separating it into a service.

2023-10-30 13:51 UTC, MartinPetrakiev commented on DeskReserve/Data/DBContext/Entity/Room.cs
Try including more Data Annotations to the entity. For example, Default Value, Required...

2023-10-31 15:15 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +        private readonly ApplicationDbContext _context;
DbContext doesn't belong here.

2023-10-31 15:16 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +            _context = context;
What if the context is null ?

2023-10-31 15:17 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +        // GET: api/Rooms
NO point of this comment.
Remove all from the Rest methods

2023-10-31 15:17 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +        private bool RoomExists(Guid id)
all other endpoints are asynchronous, this one ?

2023-10-31 15:18 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +        public async Task<IActionResult> PutRoom(Guid id, Room room)
Please provide Request objects for Save and update of entity!

2023-10-31 15:18 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +            if (id != room.RoomId)
?

2023-10-31 15:19 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +            _context.Entry(room).State = EntityState.Modified;
Is there a purpose for keeping track of the entity modified state?

2023-10-31 15:19 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +                    throw;
throw what ?

2023-10-31 15:20 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +            return CreatedAtAction("GetRoom", new { id = room.RoomId }, room);
GetRoom isn't the correct action ?

2023-10-31 15:21 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomService.cs
> +		public List<Room> GetAllDogs()
IEnumarable

2023-10-31 15:36 UTC, GeorgiBorisovP3 requested changes

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomService.cs
> +		public List<Room> GetAllDogs()
Get all dogs ?!?!?!?!

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomService.cs
> +		{
Make it async

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +namespace DeskReserve.Controllers
Make sure to hit at least 90% coverage

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomService.cs
> +		public RoomService(ApplicationDbContext dbContext)
Please register this service to the IOC container

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +    public class RoomsController : ControllerBase
RoomController use singular

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Data/DBContext/Entity/Room.cs
> +		public int FloorId { get; set; }
Is the FLoor Guid. Also you can fetch the desired relation entity with EntityFramework.

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomService.cs
> +	public class RoomService
There is this magical thing called Interface!

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +            return room;
Always specify the return type , in this situation return Ok(room), Be consistent in all controller method

2023-10-31 15:36 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomService.cs
> +		public RoomService(ApplicationDbContext dbContext)
And use it!

2023-10-31 16:49 UTC, Stanislav-Stoychev01 requested changes

2023-10-31 16:49 UTC, Stanislav-Stoychev01 commented on DeskReserve/Controllers/RoomsController.cs
> +﻿using System;
Where is the creation script?

2023-11-16 13:11 UTC, GeorgiBorisovP3 approved these changes

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +    public class RoomsController : ControllerBase
Still pending !

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +using DeskReserve.Exceptions;
Remove redundant usings

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +        // GET: api/Rooms
Still pending !

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +			//var room = await _roomService.Get(id);
Remove

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Controllers/RoomsController.cs
> +        }*/
?

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Data/DBContext/Entity/Room.cs
> +		public Guid RoomId { get; set; }
setter on id field ?

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Data/DBContext/Entity/Room.cs
> +		public Guid FloorId { get; set; }
Instead of floorId Get the Entity instead

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/DeskReserve.csproj
> +	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
Is there any particular reason to change the package version ?

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomDto.cs
> +	public class RoomDto
Split into create and update models

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomDto.cs
> +		//public Guid FloorId { get; set; }
?

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomService.cs
> +﻿//using DeskReserve.Data.DBrepository;
?

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Domain/RoomService.cs
> +			var room = await _repository.GetOneAsync(id) ?? throw new EntityNotFoundException();
Add meaningful message to the Exception

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Mapper/RoomMapper.cs
> +		public static Room UpdateFromDto(this Room Room, RoomDto RoomDto)
This is not a mapper method!

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Program.cs
> +builder.Services.AddScoped<IRoomRepository, RoomRepository>();
Use Singleton for the Repository

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Program.cs
> +builder.Services.AddScoped<RoomsController, RoomsController>();
Remove the controller DI

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Repository/IRoomRepository.cs
> +		Task<bool> DeleteOneAsync(Guid id);
Use simpler names Get, Update, Create, Delete, why add suffix Async when the return type is Task ?

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Repository/RoomRepository.cs
> +			_context.Entry(room).State = EntityState.Modified;
Explain me why we need to track the modify state ?

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/Repository/RoomRepository.cs
> +			var exict = await _context.Rooms.FindAsync(room.RoomId) ?? throw new EntityNotFoundException();
exict ?

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve/appsettings.json
> -    "DefaultConnection": "Server=MihailPC;Database=test123;Trusted_Connection=True"
Don't commit changes in the appSettings

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve_Tests/RoomControllerTest.cs
> +﻿using DeskReserve.Domain;
Separate the tests in folder structure similar in the src, Also fix the folder structure in the src

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve_Tests/RoomControllerTest.cs
> +using System.Threading.Tasks;
Stop commiting redundant usings

2023-11-16 13:11 UTC, GeorgiBorisovP3 commented on DeskReserve_Tests/RoomMapper.cs
> +		}*/
?

2023-11-17 10:21 UTC, Stanislav-Stoychev01 approved these changes

2023-11-17 10:22 UTC, Stanislav-Stoychev01 commented on DeskReserve/Controllers/RoomsController.cs
> +        }*/
?

2023-11-17 13:00 UTC, merged